### Test user service
GET http://localhost:8001 HTTP/1.1

### Login
POST http://localhost:8001/login HTTP/1.1
Content-Type: application/json

{
    "email": "macthiem@gmail.com",
    "password": "1q2w3e4r"
}

### Get current user
GET http://localhost:8001/current HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMDExNjg3M2M3ZjQzOWExZWE0ZjciLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM4MzY5MzgwLCJleHAiOjE2MzgzNjk0NDB9.d5KCpqIzChErG2Es22RqiDjBMzfCUsgTETHaqp6Rpbc

### Get roles
GET http://localhost:8001/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMDExNjg3M2M3ZjQzOWExZWE0ZjciLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM4MzY4NDUzLCJleHAiOjE2MzgzNjg0NTN9.T48eD6Lp1SXsOjQXdQ9hWEPsglx7ljx1kQs2fui2Zhs

### Create role
POST http://localhost:8001/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZGM0Nzg1ODhiYTVlMDAwNzI2YzQiLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM2Njk1MjU0LCJleHAiOjE2MzY2OTg4NTR9.ktEqEpzm-fA0ixKwsQzp3swpSn_bQypEO9eM0Fk1GoA

{
    "name": "Bảo vệ",
    "slug": "bao-ve",
    "description": "Không tương tác với hệ thống."
}

### Show role
GET http://localhost:8001/roles/618e06c0972a9dd7837f8d47 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZGM0Nzg1ODhiYTVlMDAwNzI2YzQiLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM2Njk1MjU0LCJleHAiOjE2MzY2OTg4NTR9.ktEqEpzm-fA0ixKwsQzp3swpSn_bQypEO9eM0Fk1GoA

### Update role
PUT http://localhost:8001/roles/618e06c0972a9dd7837f8d47 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZGM0Nzg1ODhiYTVlMDAwNzI2YzQiLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM2Njk1MjU0LCJleHAiOjE2MzY2OTg4NTR9.ktEqEpzm-fA0ixKwsQzp3swpSn_bQypEO9eM0Fk1GoA

{
    "name": "Bảo vệ",
    "slug": "bao-ve-1",
    "description": "Không tương tác với hệ thống."
}

### Delete Role
DELETE http://localhost:8001/roles/618e06c0972a9dd7837f8d47 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZGM0Nzg1ODhiYTVlMDAwNzI2YzQiLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM2Njk1MjU0LCJleHAiOjE2MzY2OTg4NTR9.ktEqEpzm-fA0ixKwsQzp3swpSn_bQypEO9eM0Fk1GoA

### Get users
GET http://localhost:8001/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMDExNjg3M2M3ZjQzOWExZWE0ZjciLCJ1c2VyUm9sZSI6ImdpYW0tZG9jIiwiaWF0IjoxNjM4MzY4NjQ1LCJleHAiOjE2MzgzNjg2NzV9.aNZLX49Lnk0wtSpnT95hJh9ekxLQ0VBKozFv-wNCY_g

